dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.3.0

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0"
dotenv: .env
networks:
  default: development

  development:
    fee: 100000000000000000
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    # Tenemos todos los mocks para correr en development...

    # Y si no estamos en development tenemos los contratos reales
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"

  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
  
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  

# wallets:
#   from_key1: ${PRIVATE_KEY}

wallets:
  from_key:
    0: ${PRIVATE_KEY_0}
    1: ${PRIVATE_KEY_1}
    2: ${PRIVATE_KEY_2}
